stages:
  stage: build
  jobs:
  - job: build
    steps:  
    - task: BatchScript@1
      displayName: 'Run script src/RunBuild.bat'
      inputs:
        filename: src/RunBuild.bat
        arguments: '"Release"'
        workingFolder: src

    - task: CopyPublishBuildArtifacts@1
      displayName: 'Copy Publish Artifact: Publish'
      inputs:
        CopyRoot: src/
        Contents: |
          SFA.Tl.Matching.Automation.Tests/bin/Release/**/*.*
          *.fsx
          *.bat
          Tools\Nuget\NuGet.exe            
        ArtifactName: Publish
        ArtifactType: Container
