stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" '
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)\tests'
      inputs:
        Contents: |     
          src\**\bin\release\*.*
        TargetFolder: '$(build.artifactstagingdirectory)\tests'
        OverWrite: true

    - pwsh: Get-ChildItem -Recurse

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'appdrop'
        publishLocation: 'Container'