stages:
- stage: tests
  dependsOn: build
  jobs:
  - job: tests
    steps:
    
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'appdrop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - pwsh: Get-ChildItem -Recurse

    # - task: Tokenization@2
    #   displayName: 'Tokenization: Transform file *.json'
    #   inputs:
    #     SourcePath: '$(System.ArtifactsDirectory)/appdrop/tests'
    #     TargetFileNames: '*.json'
    
    

    # - task: VSTest@2
    #   inputs:
    #     testSelector: 'testAssemblies'
    #     testAssemblyVer2: |
    #       **\*test*.dll
    #       !**\*TestAdapter.dll
    #       !**\obj\**
    #     searchFolder: '$(System.ArtifactStagingDirectory)'
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'
# stages:
#   - stage: tests
#     jobs:
#     - job: tests
#       steps:
#       - task: DownloadBuildArtifacts@0
#         inputs:
#           buildType: 'current'
#           downloadType: 'single'
#           artifactName: 'Publish'
#           downloadPath: '$(System.ArtifactsDirectory)'

#       - task: Tokenization@2
#         displayName: 'Tokenization: Transform file *.config'
#         inputs:
#           SourcePath: '$(System.ArtifactsDirectory)/Publish'
#           TargetFileNames: '*.config'
#           RequireVariable: true
#       - task: BatchScript@1
#         displayName: 'Run script $(System.ArtifactsDirectory)/Publish/RunBuild.bat'
#         inputs:
#           filename: '$(System.ArtifactsDirectory)/Publish/RunBuild.bat'
#           arguments: '"Release" "Run Automation Suite Tests"'
#           workingFolder: '$(System.ArtifactsDirectory)/Publish'
#         continueOnError: true
#       - task: PublishTestResults@2
#         displayName: 'Publish Test Results **\Test*.xml'
#         inputs:
#           testResultsFormat: NUnit
#           testResultsFiles: '**\Test*.xml'
#           mergeTestResults: true
#           testRunTitle: 'T-Levels Matching Automation Suite TEST'