stages:
- stage: tests
  dependsOn: build
  jobs:
  - job: tests
    steps:
    
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'appdrop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - pwsh: Get-ChildItem -Recurse

    - task: Tokenization@2
      displayName: 'Tokenization: Transform file *.config'
      inputs:
        SourcePath: '$(System.ArtifactsDirectory)/appdrop/tests'
        TargetFileNames: '*.config'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
        searchFolder: '$(System.ArtifactsDirectory)/appdrop/tests'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'