resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'
  demands:
  - Cmd

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Release'
stages:
  - template: ./yaml/stages/build.yml
  - template: ./yaml/stages/runtests.yml