pool:
  name: 'Azure Pipelines'
  vmImage: 'vs2017-win2016'
  demands:
  - Cmd

name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)

variables:
  Build.MajorNumber: '0'
  Build.MinorNumber: '1'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Release'
stages:
  - template: ./yaml/stages/build.yml
  - template: ./yaml/stages/runtests.yml