resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Release'
stages:
  - template: ./yaml/stages/build.yml
  - template: ./yaml/stages/runtests.yml