pool:
  name: Continuous Integration 02 - SSD - 160ACU
  demands:
  - Cmd

steps:
- task: BatchScript@1
  displayName: 'Run script src/RunBuild.bat'
  inputs:
    filename: src/RunBuild.bat
    arguments: '"Release"'
    workingFolder: src

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: Publish'
  inputs:
    CopyRoot: src/
    Contents: |
      tl-matching-automation-suite/bin/Release/**/*.*
      *.fsx
      *.bat
      Tools\Nuget\NuGet.exe
    ArtifactName: Publish
    ArtifactType: Container